default:
  image: 
    name: runmymind/docker-android-sdk
    entrypoint: [""]
stages:
  - test
  - release
test:
  stage: test
  script:
    - cd pretixprint
    - git submodule init
    - git submodule update
    - GRADLE_USER_HOME=/cache ANDROID_HOME=/android-sdk-linux ./gradlew --no-daemon -Dmaven.repo.local=$(pwd)/repo lintDebug assembleFossDebug --stacktrace
release:
  stage: release
  script:
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - cat $KSTORE | base64 -d > release.keystore
    - cp .secure_files/ZSDK_ANDROID_API.jar pretixprint/ZSDK/
    - cp .secure_files/ZSDK_CARD_ANDROID_API.jar pretixprint/ZSDK/
    - cp .secure_files/snmp6_1z.jar pretixprint/ZSDK/
    - cp .secure_files/libevolis-release.aar pretixprint/EvolisSDK/
    - cd pretixprint
    - cat $LOCALPROP > local.properties
    - git submodule init
    - git submodule update
    - GRADLE_USER_HOME=/cache ANDROID_HOME=/android-sdk-linux ./gradlew --no-daemon -Dmaven.repo.local=$(pwd)/repo assembleFullRelease --stacktrace
  artifacts:
    paths:
      - pretixprint/app/build/outputs/apk/full/release/*.apk
    expire_in: '6 weeks'
  only:
    - '/^.*\..*$/'
variables:
  GIT_SUBMODULE_STRATEGY: recursive
