plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.kapt)
    alias(libs.plugins.license)
    alias(libs.plugins.sentry.android)
}

android {
    namespace = 'eu.pretix.pretixprint'

    compileSdk = 36

    defaultConfig {
        applicationId "eu.pretix.pretixprint"
        minSdk = 21
        targetSdk = 36
        versionCode = 84
        versionName = "2.23.0"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled = true

        base.archivesName = rootProject.name + "-" + versionName
    }

    kotlin {
        jvmToolchain {
            languageVersion.set(JavaLanguageVersion.of(17))
        }
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
        dataBinding = true
    }

    dataBinding {
        enabled = true
    }


    signingConfigs {
        release {
            storeFile file("../../release.keystore")
            storePassword System.getenv("KSTOREPWD")
            keyAlias "pretixdroid"
            keyPassword System.getenv("KSTOREPWD")
        }
    }

    buildTypes {
        def sentry_dsn = ""
        try {
            Properties properties = new Properties()
            properties.load(project.rootProject.file('local.properties').newDataInputStream())
            sentry_dsn = properties.getProperty('sentry.dsn')
            if (sentry_dsn == null) {
                sentry_dsn = ""
            }
        } catch (all) {
            sentry_dsn = ""
        }

        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            multiDexKeepProguard = file('multidex-config.pro')
            signingConfig = signingConfigs.release
            manifestPlaceholders["SENTRY_DSN"] = sentry_dsn
        }
        debug {
            debuggable = true
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
            manifestPlaceholders["SENTRY_DSN"] = ""
        }
    }

    sentry {
        uploadNativeSymbols = false
        includeNativeSources = false
        includeProguardMapping = false
        autoUploadProguardMapping = false
        telemetry = false

        tracingInstrumentation {
            enabled = false
        }

        autoInstallation {
            enabled = false
        }
    }

    flavorDimensions "edition"
    productFlavors {
        foss {
            dimension "edition"
            versionNameSuffix "-foss"
        }
        full {
            dimension "edition"
            versionNameSuffix "-full"
        }
    }
    packagingOptions {
        resources {
            excludes += [
                'META-INF/DEPENDENCIES',
                'META-INF/LICENSE',
                'META-INF/LICENSE.txt',
                'META-INF/license.txt',
                'META-INF/NOTICE',
                'META-INF/NOTICE.txt',
                'META-INF/notice.txt',
                'META-INF/ASL2.0'
            ]
        }
    }

    lint {
        abortOnError = false
        disable 'InvalidPackage', 'MissingTranslation'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.legacy.support.v4
    implementation libs.androidx.vectordrawable
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.multidex
    implementation libs.androidx.viewpager2
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.preference.ktx
    implementation libs.splitties.toast
    implementation libs.progressbutton

    // libpretixprint
    implementation printLibs.openpdf
    implementation printLibs.zxing.core
    implementation libs.android.awt

    implementation libs.joda.time
    implementation libs.sentry.android
    implementation libs.slf4j.nop

    implementation(project(':cups4j')) {
        transitive = false
    }
    implementation(project(':libpretixprint')) {
        transitive = false
    }

    implementation libs.escpos.coffee
    implementation libs.sunmi.printerlibrary
    implementation libs.sunmi.printerx

    // Evolis SDK
    fullImplementation(project(':EvolisSDK')) {
        transitive = true
    }
    fullImplementation libs.jna

    // Zebra LinkOS SDK
    // Comment == Version shipped by Zebra
    fullImplementation(project(':ZSDK')) {
        transitive = false
    }
    fullImplementation libs.bcprov.jdk15on
    fullImplementation libs.commons.codec // 1.15; already included for libpretixprint
    fullImplementation libs.commons.io // 2.2
    fullImplementation libs.commons.lang3 // 3.4
    // fullImplementation printLibs.zxing.core // 3.3.1; already included for libpretixprint
    fullImplementation libs.dom4j // 1.6.1
    fullImplementation libs.jackson.annotations // 2.2.3
    fullImplementation libs.jackson.core // 2.2.3
    fullImplementation libs.jackson.databind // 2.2.3
    fullImplementation libs.jaxen // 1.1-beta-6
    // fullImplementation libs.simple.xml // 2.7.1; depends on xpp3, fails with DuplicatePlatformClasses
    fullImplementation libs.snmp4j // 2.3.0

    implementation libs.kotlin.stdlib
    implementation libs.kotlin.reflect
    implementation libs.eventbus
    implementation libs.jackson.moduleKotlin

    implementation libs.streamsupport.cfuture
}
repositories {
    google()
    mavenCentral()
    maven { url = "https://jitpack.io" }
}
